In [2]:
import cv2
import numpy as np
import random
import os

In [12]:
imglist = os.listdir("./mainimages")
for a in imglist:
    img  = cv2.imread("./mainimages/"+a, 0)
#     cv2.imshow("image", img)
#     cv2.waitKey(0)
#     cv2.destroyAllWindows()

    
    for numrange in range (20):
        newimg = np.ones((500,500))*255
        for i in range(499):
            for j in range(499):
                if (img[i][j]==0):
                    w = random.randint(0,3) #for max number of pixels to be placed for each main pixel
                    for num_pixel in range(w):
                        y = random.randint(0,1)
                        print(y)
                        if y==1:
                            col = j+random.randint(-15, 15) #max span
                            row = i+random.randint(-15, 15)
                            if 0<=col<=499 and 0<=row<=499:
                                newimg[row][col] = 0
#         cv2.imshow("image", newimg)
#         cv2.waitKey(10)
#         cv2.destroyAllWindows()
        cv2.imwrite("./withnoise/"+a[0]+a[1]+a[2]+r"("+str(numrange)+r").png", newimg)



0
1
1
1
1
0
0
0
1
1
1
1
0
0
0
1
1
0
0
0
1
0
0
1
0
0
1
0
0
0
0
1
0
1
1
0
1
0
1
1
1
1
1
1
0
0
1
0
0
1
0
1
1
1
0
1
1
1
1
1
0
0
1
0
0
0
0
0
0
0
1
0
1
0
1
1
0
1
0
1
0
0
0
1
1
1
1
0
1
0
1
0
1
0
1
1
0
1
0
1
0
0
0
0
1
1
1
1
1
1
1
1
0
0
1
0
0
1
0
0
1
0
0
1
1
0
1
0
0
1
1
1
0
0
1
0
0
0
0
0
1
0
1
1
0
0
1
1
0
1
1
0
0
1
0
0
1
0
1
0
1
0
0
1
0
1
1
0
0
1
1
1
0
1
1
0
0
1
0
1
1
1
0
0
0
1
0
1
1
0
0
1
0
0
0
0
1
1
0
0
0
1
1
0
1
0
1
1
1
1
0
1
1
1
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
0
0
1
1
0
0
1
0
1
1
0
0
0
1
0
1
1
1
1
1
1
0
1
1
0
1
1
0
0
1
1
1
1
1
0
0
0
1
1
0
0
0
1
1
0
0
0
0
0
1
1
0
1
0
1
1
1
0
0
0
0
0
1
1
1
0
1
1
1
0
0
0
0
0
0
1
1
1
1
0
1
1
0
0
1
0
0
1
0
1
1
0
0
0
1
1
0
1
1
1
1
1
1
1
0
0
1
1
1
1
0
1
0
1
0
0
0
1
1
0
1
0
1
0
1
1
1
1
1
0
1
1
0
0
1
0
1
0
1
0
0
1
1
1
1
1
1
0
1
0
0
0
0
1
0
0
1
0
0
1
1
0
1
1
1
0
1
0
0
1
0
0
0
0
1
1
0
1
0
0
1
1
1
0
0
0
1
1
1
0
1
0
0
0
1
1
0
1
0
0
1
0
0
0
0
1
1
1
0
0
1
1
0
1
0
1
0
0
1
0
0
1
1
1
0
1
0
1
0
1
0
1
1
1
1
1
0
1
0
1
1
1
0
0
1
1
0
0
0
0
1
1
1
0
0
1
1
1
1
0
1
1
0
0
0
1
0
1
1
0


0
1
1
0
1
1
1
1
1
0
0
1
0
1
1
0
0
1
0
1
1
1
0
1
0
1
0
1
0
0
0
0
0
1
1
1
1
0
1
0
0
1
0
1
0
1
0
0
1
0
1
0
1
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
1
1
0
0
1
0
1
0
0
0
0
0
0
1
1
1
0
0
0
0
1
0
1
0
1
1
1
0
1
0
0
0
1
0
1
1
1
1
0
0
1
1
1
0
1
1
0
1
1
1
0
0
0
1
1
0
0
0
0
1
1
0
0
0
0
0
1
0
0
1
0
1
0
0
0
1
0
1
0
1
1
0
1
1
1
1
0
0
1
1
1
1
1
0
1
1
1
0
0
0
1
1
0
0
0
0
0
1
1
1
0
0
1
1
1
1
0
1
1
0
1
0
0
1
0
1
1
1
1
1
1
1
1
0
1
0
0
0
1
0
1
0
0
1
1
0
0
1
0
0
1
0
1
0
0
1
1
0
1
0
1
0
0
0
0
0
0
1
1
1
0
1
1
1
1
1
0
1
1
1
1
1
1
0
1
0
0
1
1
0
0
1
1
0
1
0
1
0
0
0
1
0
0
1
0
0
0
1
0
0
0
1
0
0
1
0
1
1
1
1
1
0
1
0
1
0
0
1
1
0
1
0
1
0
1
0
0
0
0
1
1
1
1
1
0
1
1
1
0
0
0
1
1
1
0
0
0
0
1
0
0
0
0
0
0
1
0
0
0
1
0
1
0
1
1
0
1
0
0
1
1
1
0
0
1
1
0
1
0
0
0
0
0
0
1
0
0
1
1
0
1
1
1
0
0
1
0
0
1
1
0
1
1
0
0
1
1
0
0
0
1
0
0
1
0
1
0
1
0
1
0
0
1
1
1
1
1
1
0
1
1
0
0
0
1
1
1
1
1
1
0
0
1
1
0
0
0
1
0
0
1
1
0
0
0
1
1
1
1
0
1
0
0
1
0
0
1
1
1
1
1
1
1
1
0
0
1
1
1
0
0
0
0
0
0
0
1
0
1
1
1
1
1
0
1
1
0
0
1
0
0
0
0
1
0
0
1
0
1
0
1
0
1
0
1
0
0
0
0
0
0
0


1
0
0
1
0
0
1
0
1
1
1
1
1
0
0
0
0
1
1
1
1
0
0
1
0
1
1
0
0
1
1
1
0
0
1
0
1
0
1
0
0
0
0
1
0
0
0
1
1
0
1
0
0
1
0
1
1
1
0
0
1
1
1
1
0
1
1
0
1
1
0
0
0
1
1
0
1
0
1
1
1
0
0
1
0
0
1
1
0
1
0
0
0
1
0
0
1
0
1
1
0
0
1
0
1
0
0
0
1
0
0
0
0
1
1
1
1
1
0
0
0
0
1
1
0
0
1
0
1
1
1
0
0
0
0
0
1
0
0
0
1
1
1
0
1
1
0
0
0
0
1
0
1
0
0
0
0
0
1
1
1
0
0
0
1
1
0
0
1
1
0
1
1
0
1
1
0
0
0
1
0
1
1
0
0
0
1
0
0
1
1
0
1
1
1
1
0
0
0
0
0
0
1
1
0
1
0
1
1
0
1
1
0
0
0
1
1
1
0
1
0
0
0
0
1
0
1
1
0
0
1
1
1
1
1
1
1
1
1
1
1
0
1
1
0
0
0
1
0
1
0
0
0
1
1
0
1
0
0
0
0
0
0
1
1
1
0
1
0
1
0
1
0
0
1
1
0
0
1
0
0
1
1
0
1
1
0
1
0
1
1
0
0
0
1
0
1
0
0
0
1
0
1
1
1
0
1
1
1
1
0
0
0
0
0
0
0
1
1
1
0
1
1
0
0
0
1
1
1
0
1
1
1
1
0
1
0
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
1
0
1
1
1
1
1
1
1
1
1
1
0
1
1
0
0
1
1
0
1
1
1
0
1
1
0
0
0
1
1
0
0
1
1
0
0
0
0
0
0
1
0
0
0
1
1
1
1
0
1
0
1
1
1
0
1
1
0
0
1
1
0
0
1
0
1
1
1
1
1
1
1
0
1
1
1
1
0
1
1
1
0
1
1
1
0
1
1
0
0
0
1
1
1
0
1
1
0
0
0
0
0
0
1
0
0
1
0
0
0
0
1
1
0
0
0
0
1
1
1
1
0
0
1
0
0
0
0
0
1
0
1
0
1
1
0
0
1
0
0
0
0
0
1
0
1
0


0
0
1
1
0
1
0
1
1
1
1
0
1
0
1
0
0
0
1
0
1
0
0
1
1
0
1
0
1
1
1
0
1
0
1
1
1
0
1
1
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
1
0
0
1
0
0
0
0
1
1
0
1
1
1
1
0
1
1
0
1
0
0
1
0
1
0
1
0
0
0
0
0
1
1
1
0
1
0
1
0
1
0
0
0
0
1
1
1
1
0
0
1
0
0
0
0
1
1
1
0
1
1
1
1
1
0
1
1
0
0
0
1
0
1
1
0
0
0
1
1
0
1
1
1
1
0
1
0
1
1
1
0
1
0
0
0
0
1
1
0
1
0
0
0
0
0
0
0
0
1
0
0
0
1
1
1
1
1
0
1
0
1
1
1
0
1
0
1
1
0
1
0
0
0
1
0
1
1
1
0
0
0
0
0
1
0
1
1
0
1
0
1
1
1
1
0
0
0
0
0
1
1
0
1
0
1
0
1
1
1
0
1
0
0
0
0
0
1
1
1
0
0
0
0
0
1
0
1
1
0
0
1
1
1
0
0
1
0
0
1
1
0
1
0
0
0
0
1
0
1
1
0
1
0
1
0
1
1
0
0
0
0
0
1
1
1
1
0
1
1
1
0
1
0
1
1
0
0
0
0
0
1
0
0
0
0
0
1
0
0
1
1
0
0
1
1
0
0
0
1
0
0
0
0
0
1
0
0
0
1
0
1
0
1
0
1
1
0
1
1
1
0
0
1
0
1
0
1
0
0
1
0
1
1
1
1
1
0
0
1
0
1
0
0
1
0
1
1
0
0
1
0
1
1
1
0
0
0
1
0
0
0
0
1
0
0
0
0
0
0
1
0
1
0
0
0
1
0
1
1
0
0
1
0
1
1
0
1
1
1
0
1
1
0
1
1
0
0
1
0
0
0
0
0
1
0
0
1
0
1
0
1
0
1
1
1
1
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
1
0
1
0
1
0
0
0
1
0
1
0
0
0
1
0
0
1
0
0
1
1
1
0
1
0
1
1
1
1
0
1
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0


1
0
1
1
1
1
1
1
0
1
1
0
1
0
0
1
1
0
0
0
1
0
0
0
1
1
1
1
1
0
0
1
0
1
0
1
0
1
0
0
0
1
1
0
0
0
1
0
0
1
1
1
1
1
1
1
0
0
0
1
1
1
1
0
0
0
0
0
1
0
1
0
1
1
1
1
0
1
1
1
0
0
1
0
0
1
1
1
0
0
0
1
1
1
0
1
1
0
1
1
1
1
0
1
1
1
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
1
0
1
1
1
1
1
1
1
1
1
0
0
0
0
1
1
0
0
1
0
0
1
1
1
1
0
1
0
1
0
0
0
1
1
1
1
0
1
0
0
1
1
1
1
1
1
0
1
0
0
0
0
0
0
1
1
1
0
1
1
1
0
1
1
1
1
1
1
1
0
0
1
1
1
0
1
0
1
1
1
0
1
1
0
0
1
1
0
0
1
1
0
0
1
1
0
1
1
0
1
0
0
1
1
0
0
0
0
0
0
1
1
1
0
0
0
1
0
1
1
0
0
1
0
1
1
0
1
0
0
0
1
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
1
1
1
0
0
1
0
0
1
1
1
1
0
1
1
1
0
0
1
1
1
1
1
0
0
0
0
0
1
1
0
0
0
1
0
0
1
0
1
0
1
1
0
1
1
1
0
1
1
0
1
1
1
1
0
1
0
0
0
0
0
1
0
0
1
0
0
0
1
1
0
0
1
0
1
1
0
1
1
0
1
1
0
1
0
1
0
1
0
0
0
0
1
1
1
0
0
1
1
1
1
1
1
1
0
1
1
1
1
1
1
0
1
1
0
1
0
0
1
0
0
0
0
1
1
1
1
1
0
0
0
0
0
1
1
0
1
1
0
1
0
0
1
1
1
0
0
1
0
1
0
0
0
0
1
1
0
0
1
0
0
1
0
1
0
0
1
0
0
1
0
1
0
1
0
0
1
1
0
0
0
0
0
0
1
0
1
1
0
1
1
1
1
0
1
1
1
0
1
1
0
1
0
0
1
0
0
1
0
1
0
1
1
0
0
0
1
0
0
0
1
1
0
0
1
0
1
1
0


1
1
0
0
0
0
0
1
0
1
1
1
0
0
0
1
0
1
1
0
1
1
0
0
1
0
0
0
1
1
1
0
0
1
1
1
1
1
0
1
1
0
0
0
0
1
0
1
1
1
0
0
1
0
1
1
1
0
1
1
0
0
0
1
1
0
1
1
1
1
1
0
0
1
1
1
0
0
0
0
1
1
0
1
0
1
0
0
0
1
0
1
1
0
0
1
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
1
0
0
1
0
0
1
0
0
0
0
0
1
0
1
1
0
1
0
0
1
0
0
1
1
0
1
1
1
1
0
1
0
1
1
1
1
0
1
1
0
1
0
1
1
0
0
0
1
1
1
0
0
0
1
1
0
0
0
1
1
1
0
1
1
1
0
1
0
0
1
0
0
0
1
0
1
1
0
0
0
0
1
0
0
1
0
0
0
1
0
0
0
1
1
1
1
0
0
1
0
1
1
0
0
0
0
1
1
1
0
1
0
0
0
0
1
0
1
0
0
1
1
0
0
1
1
0
0
0
0
0
0
0
0
1
1
1
0
0
1
0
1
0
0
0
0
0
1
1
0
1
0
0
0
0
1
1
1
0
0
0
1
1
1
1
0
0
0
1
1
0
0
1
0
0
0
0
0
0
1
1
1
0
1
0
1
0
0
1
1
0
1
1
0
1
0
1
1
0
1
1
1
0
1
1
0
1
0
0
1
0
0
0
0
1
1
0
1
0
1
1
0
0
0
0
1
0
1
0
0
1
1
0
1
0
0
1
1
0
0
0
1
0
0
1
0
1
0
0
1
0
1
0
0
0
0
1
0
0
0
1
0
0
0
0
0
1
1
0
1
1
1
1
0
1
1
1
1
0
0
0
1
1
0
0
0
0
1
1
0
0
1
0
1
0
0
1
0
0
1
0
1
1
0
0
1
1
0
1
0
1
0
0
0
1
1
1
0
1
0
1
1
1
1
0
0
1
1
0
0
1
1
1
0
0
0
1
1
1
1
1
0
1
0
1
1
0
1
0
0
0
0
0
1
0
0
1
1
0
0
1
0
1
1
0
0
1
1
1
0
1
1
1
1
0
0
0
0
1
1
0
1
1
0
1
1
0
0


0
0
1
0
0
1
0
0
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
1
0
1
1
0
0
1
0
1
1
0
1
0
1
0
0
1
1
0
0
1
0
0
1
0
1
1
0
0
0
0
0
0
0
1
0
0
0
0
1
1
1
1
1
0
0
1
1
1
1
0
0
1
0
0
0
0
0
1
1
0
0
0
0
0
0
1
0
1
0
0
1
0
1
0
0
1
1
1
1
0
0
1
1
1
1
1
0
0
1
0
0
1
0
0
0
0
1
1
1
0
1
0
1
1
0
1
0
1
1
1
1
1
0
1
1
0
1
1
0
1
1
1
1
1
1
0
0
0
0
0
0
0
0
1
1
0
0
0
0
1
1
0
0
1
0
0
1
1
1
0
0
0
1
0
1
0
1
0
0
0
1
0
1
0
0
0
0
0
0
1
0
0
0
1
1
1
0
0
0
0
0
0
0
1
1
0
1
1
1
0
1
0
1
0
0
1
1
0
0
1
0
0
0
1
0
1
0
1
1
0
0
0
0
1
0
1
0
0
0
0
0
1
0
0
1
0
0
1
1
0
0
1
0
0
0
1
1
1
0
0
0
1
1
0
0
1
1
1
1
0
1
0
1
0
1
1
1
0
0
0
1
1
1
0
1
1
1
1
0
1
1
0
0
0
0
0
0
1
1
0
0
0
0
0
1
1
1
1
0
1
1
0
0
0
1
1
1
1
0
0
1
1
0
1
0
1
1
0
0
1
0
1
1
0
1
1
1
1
1
0
1
1
1
0
0
0
1
1
1
1
1
1
0
1
0
0
0
0
0
0
1
1
0
1
0
1
1
1
0
1
0
0
0
1
1
0
1
0
1
1
0
0
1
0
1
0
0
1
0
0
1
1
1
1
0
1
1
1
1
1
0
1
0
0
0
1
1
0
1
1
1
1
0
0
1
1
1
1
0
0
0
0
0
0
0
0
1
0
0
1
1
0
0
1
0
0
1
1
1
1
0
0
0
0
1
1
0
1
0
0
1
1
1
0
1
0
0
0
0
0
1
1
0
0
1
0
1
0
1
0
0
0
0
0
1
1
1
1
0
1
1
0
0
0
1
0
1
1
0
1
0
0
1
0
1


In [12]:
# for i in range(99):
#     for j in range(99):
#         if (img[i][j]==0):
#             w = random.randint(0,5)
#             for num_pixel in range(w):
#                 y = random.randint(0,1)
#                 if y==1:
#                     x = j+random.randint(-5,5)
#                     img[i][x] = 1
    
            
#     if (0 in img[i]):
#         x = i+random.randint(-5,5)
#         if (x<100):
#             img[i+random.randint(-5,5)][random.randint(0,99)] = 0

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [7]:
print(img)
cv2.imwrite("testout.png", img)
cv2.imshow("img", img)
cv2.waitKey(0)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


-1